INSERT INTO ROOM (ROOM_ID, BUILDING, ROOM_NUMBER, SEATS, TYPE) VALUES (1, 'A', 104, 34, 1);
INSERT INTO ROOM (ROOM_ID, BUILDING, ROOM_NUMBER, SEATS, TYPE) VALUES (2, 'A', 204, 33, 2);
INSERT INTO ROOM (ROOM_ID, BUILDING, ROOM_NUMBER, SEATS, TYPE) VALUES (3, 'B', 101, 22, 2);
INSERT INTO ROOM (ROOM_ID, BUILDING, ROOM_NUMBER, SEATS, TYPE) VALUES (4, 'H', 107, 55, 3);
INSERT INTO ROOM (ROOM_ID, BUILDING, ROOM_NUMBER, SEATS, TYPE) VALUES (5, 'H', 004, 19, 0);

INSERT INTO TUTOR (TUTOR_ID, CHANGETIME, FIRSTNAME, LASTNAME, TITLE) VALUES (1, 15, 'Stephan', 'Anft', '');
INSERT INTO TUTOR (TUTOR_ID, CHANGETIME, FIRSTNAME, LASTNAME, TITLE) VALUES (2, 25, 'Joachim', 'Sauer', 'Dr.');
INSERT INTO TUTOR (TUTOR_ID, CHANGETIME, FIRSTNAME, LASTNAME, TITLE) VALUES (3, 11, 'Frank', 'Zimmermann', 'Prof. Dr.');

INSERT INTO CENTURIA (CENTURIA_ID, CHANGE_TIME, LETTER, NBR_OF_STUDENTS, PROGRAM, "YEAR") VALUES (1, 15, 'a', 30, 'Winf', 12);
INSERT INTO CENTURIA (CENTURIA_ID, CHANGE_TIME, LETTER, NBR_OF_STUDENTS, PROGRAM, "YEAR") VALUES (2, 11, 'b', 30, 'BWL', 13);
INSERT INTO CENTURIA (CENTURIA_ID, CHANGE_TIME, LETTER, NBR_OF_STUDENTS, PROGRAM, "YEAR") VALUES (3, 17, 'b', 30, 'Wing', 14);

INSERT INTO COURSE (COURSE_ID, NAME, TYPE, TUTOR_ID) VALUES (1, 'VWL', 1, 1);

INSERT INTO EVENT ("BEGIN", "END", COURSE_ID) VALUES ('2015-10-02 12:00:00', '2015-10-02 12:45:00', 1);

INSERT INTO COURSE_CENTURIA (CENTURIA_ID, COURSE_ID) VALUES (1, 1);

INSERT INTO COURSE_ROOM (ROOM_ID, COURSE_ID) VALUES (1, 1);